name: Deploy to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: premium-469623
  SERVICE_NAME: gcp-backend
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build and push
        run: |
          gcloud builds submit backend --tag gcr.io/${PROJECT_ID}/${SERVICE_NAME}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          allow_unauthenticated: true

